networks:
  event_localhost:
services: 
  consultoriopsico:
        container_name: consultoriopsicoapi      
        image: bestlinux/consultoriopsico-api
        build: 
          context: .
          dockerfile: Dockerfile
        depends_on:
          - "sql"
        ports:
        - "8000:80"
        - "8001:443"
        environment:
          ASPNETCORE_URLS: "https://+;http://+"
          ASPNETCORE_HTTPS_PORT: "8001"
          ASPNETCORE_ENVIRONMENT: Development
          Kestrel:Certificates:Default:Path: /root/.aspnet/https/ApiConsultorio.pfx
          Kestrel:Certificates:Default:Password: 20032014@        
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: "sql_server2022-psico"
    container_name: sql_server2022-psico
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=20032014Amor@@
      
  consultoriopsico-ui:
    container_name: consultoriopsico-ui
    image: bestlinux/consultoriopsico-ui
    build:
      context: C:\Users\bestl\OneDrive\projetocida\FrontEndConsultorio\ConsultorioUI
      dockerfile: C:\Users\bestl\OneDrive\projetocida\FrontEndConsultorio\ConsultorioUI\Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
      - 8081:8081
